import { css } from '@emotion/react';

export const styles = {
  card: css({
    background: 'linear-gradient(135deg, #ffffff 0%, #f8fafc 100%)',
    borderRadius: 20,
    border: '1px solid rgba(0, 0, 0, 0.08)',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '0 2px 12px rgba(0, 0, 0, 0.04), 0 1px 3px rgba(0, 0, 0, 0.08)',
    overflow: 'hidden',
    transition: 'all 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
    position: 'relative',
    ':hover': {
      boxShadow: '0 12px 40px rgba(0, 0, 0, 0.08), 0 4px 16px rgba(99, 102, 241, 0.08)',
      transform: 'translateY(-3px)',
      borderColor: 'rgba(99, 102, 241, 0.2)',
    },
  }),
  header: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: '44px',
    padding: '0 4px 0 8px',
    borderBottom: '1px solid rgba(0, 0, 0, 0.06)',
    background: 'rgba(248, 250, 252, 0.8)',
    backdropFilter: 'blur(10px)',
  }),
  dragArea: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '32px',
    height: '32px',
    borderRadius: '8px',
    cursor: 'grab',
    transition: 'all 0.2s ease',
    ':hover': {
      background: 'rgba(0, 0, 0, 0.05)',
    },
    ':active': {
      cursor: 'grabbing',
      background: 'rgba(0, 0, 0, 0.1)',
    },
  }),
  gripIcon: css({
    color: '#64748b',
    opacity: 0.5,
    transition: 'opacity 0.2s ease',
    ':hover': {
      opacity: 0.8,
    },
  }),
  titleSection: css({
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    paddingLeft: '10px',
    paddingRight: '10px',
  }),
  title: css({
    margin: 0,
    fontSize: '15px',
    fontWeight: 600,
    color: '#1e293b',
    letterSpacing: '-0.025em',
    lineHeight: 1.4,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    maxWidth: '100%',
  }),
  actions: css({
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  }),
  dragDot: css({
    width: 14,
    height: 14,
    background:
      'repeating-linear-gradient(45deg, #ced4da, #ced4da 2px, transparent 2px, transparent 4px)',
    borderRadius: 3,
  }),
  body: css({
    padding: 24,
    flex: 1,
    minHeight: 0,
    overflow: 'auto',
    // Custom scrollbar styling
    '::-webkit-scrollbar': {
      width: '4px',
      height: '4px',
    },
    '::-webkit-scrollbar-track': {
      background: 'transparent',
    },
    '::-webkit-scrollbar-thumb': {
      background: 'rgba(0, 0, 0, 0.1)',
      borderRadius: '2px',
      transition: 'all 0.2s ease',
    },
    '::-webkit-scrollbar-thumb:hover': {
      background: 'rgba(0, 0, 0, 0.2)',
    },
    // Firefox scrollbar
    scrollbarWidth: 'thin',
    scrollbarColor: 'rgba(0, 0, 0, 0.1) transparent',
  }),
  btn: css({
    border: '1px solid #dee2e6',
    padding: '6px 12px',
    borderRadius: 8,
    background: '#fff',
    fontSize: 12,
    fontWeight: 500,
    cursor: 'pointer',
    color: '#dc3545',
    transition: 'all 0.2s ease',
    ':hover': { 
      background: '#f8f9fa',
      borderColor: '#dc3545',
      color: '#dc3545',
    },
  }),
  editBtn: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '32px',
    height: '32px',
    border: 'none',
    borderRadius: '8px',
    background: 'transparent',
    cursor: 'pointer',
    color: '#64748b',
    transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
    opacity: 0.6,
    ':hover': {
      background: 'rgba(59, 130, 246, 0.1)',
      color: '#2563eb',
      opacity: 1,
      transform: 'scale(1.05)',
    },
    ':active': {
      background: 'rgba(59, 130, 246, 0.15)',
      transform: 'scale(0.95)',
    },
  }),
  deleteBtn: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '32px',
    height: '32px',
    border: 'none',
    borderRadius: '8px',
    background: 'transparent',
    cursor: 'pointer',
    color: '#64748b',
    transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
    opacity: 0.6,
    ':hover': {
      background: 'rgba(239, 68, 68, 0.1)',
      color: '#dc2626',
      opacity: 1,
      transform: 'scale(1.05)',
    },
    ':active': {
      background: 'rgba(239, 68, 68, 0.15)',
      transform: 'scale(0.95)',
    },
  }),
};
